### ISSUE TITLE
Convert to ES2015

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#253]
Can I convert it to ES2015?

In case you don't know how it works... I progressively convert the whole code to ES2015 and then create an NPM script that uses Babel to export an ES5 version that is published to NPM.

I would do it in parts, creating pull requests for each piece individually, in such a way that nothing is broken.

Are you interested?

**Comment by xivSolutions** [comment]
@andrerpena - We're actually looking at implementing an ES2015 version of the lib (a re-write, basically). My understanding is that, with Node 6.0 there is 96% ES2015 compatibility with Node and V8. It's taking a while because of time constraints. 

Would be happy to hear your thoughts on the matter, and always happy to have contributions. Just may be a bit before the initial MVP/"spike" code is out here for work. 

Our thinking was to leave v2 in its current form until then though, and allow v3 to be the new shiney thing. 

@robconery may feel differently on these points, but to me, it makes more sense to re-write the thing to specifically take advantage of ES2015 features from the Massive API all the way down, instead of simply porting the existing code via Babel.

**Comment by andrerpena** [comment]
@xivSolutions , thank for the reply.

Disclaimer: I just got here and your opinion is more valuable than mine, these are just my 2 cents.

If you are planning to rewrite Massive anyway, then the ES2015 conversion could go along with it. Otherwise, I don't see why a rewrite would be better than progressively change it. I think the majority of ES2015 features ([listed here](https://github.com/lukehoban/es6features#introduction)) are architecturally compatible with ES5 code. Please let me know if/why you don't agree.

I would do it like this:

1. Create a ES2015 branch.
2. Add Babel and implement build scripts.
3. Starting replacing code: Start using imports, arrow functions, string interpolation, destructoring... without actually changing functionalities.
4. Merge back to master on every iteration once it's tested.

Please let me know your thoughts.

**Comment by robconery** [comment]
We've talked a lot about this - yeah the only reason to rewrite anything would be to take advantage of ES2015. As @xivSolutions mentioned, we're waiting a bit to see what happens with Node adoption. 

Also, we can change the API significantly with some of the new capabilities. I do appreciate your offer, but I want to wait a bit until we know a bit more.

**Comment by andrerpena** [comment]
Ok, I appreciate it.
Feel free to close this issue if you want.

**Comment by dmfay** [comment]
v3 (in progress!) will be using ES6 features.
