### ISSUE TITLE
Is there a way to do date between checking?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#350]
I am looking to be able to do something like:

`select * from event where '2017-02-28T17:35:00.000Z' between start_date and end_date`.  I tried:

`.find({start_date >=:'2017-02-28T17:35:00.000Z', end_date <=: ''2017-02-28T17:35:00.000Z'})`

but that did not work.

**Comment by dmfay** [comment]
There is nothing that generates a condition with the `BETWEEN` keyword (yet! although it'll probably take some doing since so far it only supports binary operators). However, plain date comparisons do work. Yours look backwards -- you want to find `start_date`s _before_ the timestamp and `end_date`s after.

**Comment by jnystrom** [comment]
I am given a date, and I am trying to get a record that falls inside the range of `startDate` and `endDate`, so I dont think my massive find code is wrong.  I am trying to just create a `.sql` file that will do the between, and see if that works.

**Comment by dmfay** [comment]
Your `find` criteria are looking for a record with `start_date >= x` and `end_date <= x`, so the only matching records will have a start_date after/equal to x and an end_date before/equal to it, therefore a start_date after or equal to the end_date.

**Comment by xivSolutions** [comment]
Unless I'm missing something (always a possibility), in your example, it looks like you are basically excluding *any* records where the start date is not equal to `2017-02-28T17:35:00.000Z`

In other words, *this* statement:
```js
.find({start_date >=:'2017-02-28T17:35:00.000Z', end_date <=: ''2017-02-28T17:35:00.000Z'})
```

Has the exact same Date/Time for both start and end date. Is this what you meant?

Also, in the case of this type of comparison, you will need to wrap the property names and comparison operators in quotes so that Massive can identify the entire property name (for the purpose here, Massive treats the column name and the comparison operator together as a property name, as you can see by the way you are assigning the value to the right of the colon):

```js
.find({ 'start_date >=': '2017-02-28T17:35:00.000Z', 'end_date <=': '2017-02-28T17:35:00.000Z' })
```

JS does not allow property names like `{ my property name: 'some name' }` but it will allow:

`{ 'my property name': 'some name' }` or...wait for it... `{ 'start_date >=': '2017-02-28T17:35:00.000Z' }`

(It is one of the slightly annoying things I wish we could find a way to deal with more elegantly...)

**Comment by jnystrom** [comment]
@dmfay and @xivSolutions you are both correct..and that was my problem.  The range is working for me...thanks you both!
