### ISSUE TITLE
How to define where scripts are located and point massive to that folder.

### ISSUE THREAD

**Issue by SBrinkworth** [dmfay/massive-js#355]
Im currently mentoring at a web development bootcamp and when we have students set up their projects, their file structure looks like this.

```
|--db
|--server
|  |--index.js
```

Most of the time this file structure works, but sometimes it cant find the db folder. When this happens, the easy fix is to move the db folder to the server folder like this.

```
|--server
|  |--index.js
|  |--db
```

How is the location of the db file determined and how can I force it to be more consistent? When working as a group, this is very frustrating because sometimes two db folders are required for the project to work on everyones computers.

**Comment by dmfay** [comment]
Unless you specify `scripts: path/to/directory` in the init block, the /db directory is assumed to be located in the current working directory. Are some students running the server from the project root and others from /server?

**Comment by SBrinkworth** [comment]
Yes, some students run the server from the project root and others from the /server. In the former, it works every time because it is both in the project root and next to the server file. However the later fluctuates between the two. I have tried adding a `scripts: path/to/directory`, but it was really buggy and so I'm not sure if I implemented it correctly or not. 


```
var massiveServer = massive.connectSync({
	connectionString: 'massive uri',
	scripts: __dirname + './../db'
});
```

**Comment by dmfay** [comment]
`path.join` should give you better results than concatenation if you decide to go that route, but since you're presumably not doing anything out of the ordinary with script sourcing I'd try to get a consistent layout and startup process working first. Especially important is having everyone start the application from the same location every time, since the scripts directory is located relative to the _process_ working directory.

The project structure I use with Massive looks like this:

```
project/
  |-db/
  |-lib/
  |-node_modules/
  |-app.js
```

where app.js is the module entrypoint which initializes Massive, analogous to your server/index.js. Startup is `node app.js` from the `project` directory.
