### ISSUE TITLE
Flaky Loading of Script Files

### ISSUE THREAD

**Issue by TomPridham** [dmfay/massive-js#387]
I'm using V3 on my local machine and everything works fine, but when I pulled the changes to my server, Massive fails to load all the scripts in my db folder about half the time. I have the db folder at the same level as my server folder. My db folder has schema and company subdirectories with the scripts in them. I'm connecting using the below.

```javascript
massive(connectionString)
    .then(db => {

        db.schema.company()
            .then(() => {
                console.log('company table is ready, checking default company');
                return db.company.get_company(1)
            })
            .then(result => {
                if (result.length === 0) {
                    db.company.new_company('company',
                        'company.com',
                        '',
                        '',
                        'whatever',
                        'UT',
                        11111);
                    console.log('company entry added')
                }
            })
            .catch(err => {
                console.log(db);
                console.log(`failed to initialize company table because: ${err}`)
            })
        app.set('db', db);
        app.use('/', require('./routes')());

        app.listen(config.port, () => {
            console.log(`listening on port ${config.port}`)
        });
    });
```

I haven't been able to find anything that directly seems to cause it. If I restart the server file a few times, I can catch it pulling the files in correctly as well as failing to. They get pulled into the functions array on the Massive object in both cases, but the failing case doesn't assign them correctly to the company and schema properties. The below were captured about 30 seconds apart with nothing else running on the server and nothing happening besides me hitting `ctrl+c` and running `node server.js`.

Failing case: 
``` 
company    : {
            schema           : 'public',
            name             : 'company',
            db               : [Circular],
            delimitedName    : '"company"',
            delimitedSchema  : '"public"',
            fullname         : 'company',
            delimitedFullName: '"company"',
            pk               : 'id',
            insertable       : true
        },
```

Correct case: 
``` 
company    : {
        schema           : 'public',
        name             : 'company',
        db               : [Circular],
        delimitedName    : '"company"',
        delimitedSchema  : '"public"',
        fullname         : 'company',
        delimitedFullName: '"company"',
        pk               : 'id',
        insertable       : true,
        check_domain     : [Function],
        delete_company   : [Function],
        get_all_companies: [Function],
        get_company      : [Function],
        new_company      : [Function],
        update_company   : [Function]
    },
```

**Comment by dmfay** [comment]
Overloading tables with scripts like that -- having both a `company` table and a `db/company` scripts directory -- isn't supported, although it looks like I missed bringing that note over from the v2 docs. So the short answer is "name your company scripts directory something else" :)

That said, your example seems pretty reasonable and it should be possible to handle overloading for attach/detach to compose and decompose objects (what's happening in your 'failing case' is that the `company` script namespace resolves first, but then the `company` table is constructed and replaces it). If you're interested in implementing it yourself, I welcome pull requests; otherwise, I'll put it on the docket.

**Comment by TomPridham** [comment]
That fixed it. Thanks!
I'd definitely be willing to try it. Where would be a good place to start with that?

**Comment by dmfay** [comment]
The relevant code is in lib/database.js, specifically the functions `attach` and `detach`: https://github.com/dmfay/massive-js/blob/master/lib/database.js#L55

`attach` should test whether something already exists on the instance at `spec.path` and behave accordingly, adding scripts to an existing Queryable/Table or replacing script namespaces with a new Queryable/Table and adding the function executors back depending on what the 'something' is. Since `reload` introspects tables, views, functions, and scripts in parallel either situation may occur.

`detach` might not even need modification; it's not really intended for public use so I don't think we need to be super-strict about decomposing entities piece by piece. Definitely test that out rather than just taking my word for it, though!

**Comment by vitaly-t** [comment]
That, plus I'm guessing that `db.company.new_company` should actually be `return db.company.new_company`, if it returns a promise.
