### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by treicadani** [dmfay/massive-js#392]
I am unable to use massive version 3.x as the following message comes up

>  (node:18920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): error: relation "pg_matviews" does not exist

I could not find anything about this "pg_matviews" in search engines.
I am using Postgres version 9.4

Code:

```
var massive = require('massive');

var config = {
    host: "127.0.0.1",
    port: 5432,
    database: "db",
    user: "postgres",
    password: "pwd"
};

massive(config).then(db => { db.run('SELECT * FROM schema.table').then(r => { console.log(r) });
```

**Comment by vitaly-t** [comment]
> I could not find anything about this "pg_matviews" in search engines.

What search engines did you try? Google immediately takes you to the official documentation: https://www.postgresql.org/docs/9.3/static/view-pg-matviews.html

That table has got to be there, or else I don't know what type of PostgreSQL installation that is...

**Comment by treicadani** [comment]
Sorry, I meant that I haven't found anything related to the issue, not the actual definition.

I have uploaded here a screenshot with the version of PostgreSQL installation in my Linux box https://unsee.cc/sodupame/

I will look up for Materialized Views to see why they missing, i may have to reinstall and i will come back with a result.

Thanks.

**Comment by vitaly-t** [comment]
> I will look up for Materialized Views to see why they are missing

This must be the case ;)

**Comment by treicadani** [comment]
I have re-installed PostgreSQL on the box and was still the same (i guess there is something odd with CentOS 6.8).
But then I have created a new Debian box, installed PostgreSQL 9.4 and I am back in business.

**Comment by dotob** [comment]
hi, i happily used massive with postgres 8.3 until now. after the update i get this error. i do not understand why i cannot disable this? please help.

sebastian

**Comment by vitaly-t** [comment]
No idea if it is possible to disable, perhaps @dmfay knows ;)

**Comment by dmfay** [comment]
@dotob wow, which version of Massive did you upgrade from? Materialized views have only been present in Postgres since 9.3 so it makes sense that the query which looks in `pg_matviews` wouldn't work on an older server version, but that query was introduced in v2.2.0 almost two years ago.

Adding the option to disable it should be pretty straightforward, at least.

**Comment by dmfay** [comment]
@dotob `massive(connection, {excludeMatViews: true})` should take care of that. I don't have easy access to an 8.3 instance, so let me know how it goes!

**Comment by michaelzoidl** [comment]
@dmfay tried your solution, works fine 👍 
One question, when do you plan to release this? 

I've installed it from the master branch, but honestly this is not something i will use in production :)

**Comment by dmfay** [comment]
v4.4.0 is out, I was just waiting to see if anyone ran into other issues with legacy Postgres instances.

**Comment by michaelzoidl** [comment]
Awsome! Thanks for the fast process :) 

One question, whats the reason for the usage of the `pg_matviews`  table usage? I mean, if i can toggle it, why do i need it at the first place?

**Comment by dmfay** [comment]
Materialized views are really useful. Unlike normal views which run their stored query every time you select from them, materialized views cache their results so you can get near-instant reads from queries that usually take a long time to run. Of course there's a catch: you have to refresh the data asynchronously, so you have to be willing to read potentially stale data.

If you don't have or need any materialized views, you can turn the feature off, but it's not really hurting anything. The only real reason for the toggle is because people are still using older versions of Postgres which don't have materialized views, therefore no `pg_matviews` table, therefore the query that tries to pull information from `pg_matviews` throws and they can't connect.
