### ISSUE TITLE
Monitoring Queries

### ISSUE THREAD

**Issue by tadejstanic** [dmfay/massive-js#400]
I want to monitor queries by following this example in the guide:

```
const massive = require('massive');
const monitor = require('pg-monitor');

massive('postgres://localhost:5432/massive').then(db => {
  monitor.attach(db.driverConfig);

  db.run('select 1').then(data => {
    // monitor output appears in the console
  });
});
```
But the returned Massive instance doesn't have 'driverConfig' property, so pg-monitor cannot start monitoring the events.

**Comment by dmfay** [comment]
I exposed that property and documented the pg-monitor setup after the 3.0.0-rc1 release -- if you pull `master` instead of the RC release, it'll work, or if you'd rather wait a bit I should have v3 proper out within the next couple days. I'll look into separating the doc build process so they'll track the latest release instead of the repo itself.

**Comment by dmfay** [comment]
That's all taken care of.

**Comment by tadejstanic** [comment]
thx @dmfay  for your work!
