### ISSUE TITLE
Warning when reloading database

### ISSUE THREAD

**Issue by MadsRC** [dmfay/massive-js#414]
Upon creating massive() instance, I run the following script to make sure my tables are present:

```
BEGIN;
	CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
	CREATE TABLE IF NOT EXISTS policies (
	  ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  body JSONB,
  createdat DATE DEFAULT now()
);
	CREATE TABLE IF NOT EXISTS users (
	  ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  body JSONB,
  createdat DATE DEFAULT now()
);
	CREATE TABLE IF NOT EXISTS hostgroups (
	  ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  body JSONB,
  createdat DATE DEFAULT now()
);
	CREATE TABLE IF NOT EXISTS hosts (
	  ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  body JSONB,
  createdat DATE DEFAULT now()
);
END;
```

However, I noticed that since the initialization of the massive() instance happens before the init script is run, the tables won't be present in the massive() instance. If the tables were present when creating the massive instance, they are available in the massive() instance.

The documentation says to run db.reload() to fix this, and I solved it this way:
```
var massive = require('massive');
var config = require('./config.js');
var connectionInfo = 'postgres://'+config.database.user+':'+config.database.password+'@'+config.database.host+'/'+config.database.database;

module.exports = function database() {
  return new Promise((resolve, reject) => {
    massive(connectionInfo)
    .then(instance => {
      instance.initdb()
      .then(_ => {
        instance.reload().then(_ => {
          resolve(instance);
        })
        .catch(err => {
          reject(err);
        })
      })
      .catch(err => {
        reject(err);
      })
    })
    .catch(err => {
      reject(err);
    })
  });
}
```

Which works, but throws the following warning:
```
WARNING: Creating a duplicate QueryFile object for the same file -
    /app/app/db/initdb.sql
    at files.map.f (/app/node_modules/massive/lib/loader/scripts.js:14:21)
    at Promise.then.files (/app/node_modules/massive/lib/loader/scripts.js:13:24)
```

Am I doing it the wrong way? From what I gather from the documentation of Massive-js and pg-promise I shouldn't have to close the connection and opening a new one - However I did try to call instance.pgp.end() to no avail.

**Comment by vitaly-t** [comment]
The warning comes from pg-promise when creating multiple `QueryFile` objects for the same file. That type works as a link, with the ability to auto-reload a changed file, so creating more than one such link is a waste of IO, and thus considered an anti-pattern, hence the warning.

It happens on this line: https://github.com/dmfay/massive-js/blob/master/lib/loader/scripts.js#L14

which seems to be able to supress warnings by passing option `noWarnings: true` during the library's initialization.

**Comment by dmfay** [comment]
I have to admit that issuing DDL on init was not a use case I'd anticipated! `reload` is indeed meant to pick up structural changes without a full teardown, so you're doing that right and Massive should use the QueryFile autoreload instead of reinitializing everything like it does right now. But it does sound like you might want to investigate a more formal db setup/migration process if you're currently unsure whether your structure will be there or not when you start the app.

QueryFiles persist even after a connection close so disconnecting wouldn't help with the warning. It isn't really hurting anything right now, but the instance passed to the loader has a collection of executables so that should help with reloading existing files in place.
