### ISSUE TITLE
SaveDoc not creating a new document if id doesn't exist in database.

### ISSUE THREAD

**Issue by karsai5** [dmfay/massive-js#462]
The documentation says that when using the SaveDoc function with an id supplied its expected behaviour should basically by an upsert. If it finds the ID that you provide it updates the document, otherwise, it inserts a new document with that ID. 

I'm running into an issue where if I use saveDoc to insert a new value with a specified (not yet in the database) ID nothing gets inserted and the value returned is `null`. Using saveDoc with the ID of an existing document successfully updates the document and using saveDoc without an ID will insert with an auto-incremented ID without any issues. 

Here's an example of the current behaviour.

Assuming we have a DB with the following table
```
people_table:
|id|firstname|lastname|
|1|John|Doe|
|2|James|Smith|
```

```db.people_table.saveDoc({firstname: 'linus', lastname: 'karsai'});```
returns the inserted DB object with ID.
```db.people_table.saveDoc({id: 2, firstname: 'linus', lastname: 'karsai'});```
will update the document in the database with ID = 2.
```db.people_table.saveDoc({id: 45, firstname: 'linus', lastname: 'karsai'});```
will return `null`, won't insert into the database and doesn't throw any errors. From my understanding of the docs, the expected behaviour should be that it inserts in the DB with the ID given and returns that document.

**Comment by karsai5** [comment]
I was originally running version 3.2.2 and it would throw the following error: `can't find body of null`. Then I updated to version 4.0.0 and have the problem described above.

**Comment by dmfay** [comment]
ah, that's a bit of a tricky one. `save` and `saveDoc` are not true upserts in that they insert the record if the id value is not found and update it otherwise. Rather, what happens is that these functions check the data _you_ provide for a primary key value to decide whether they should emit an `INSERT` or an `UPDATE`.

Since you're passing a document with `id` 45, `saveDoc` recognizes that the primary key is set and emits an `UPDATE`; but since the corresponding record # 45 does not exist in the database, obviously no rows are affected. How are you generating your `id`? Stock document tables have a serial primary key so it will be autogenerated.

**Comment by karsai5** [comment]
Thought it might be something similar to that. The documentation should be reworded to clarify that. The section below made me think that if it _can_ find it it'll update it _otherwise_ it will insert with the given ID. Maybe even just pointing out that this isn't an upsert method (like you did just now) will help future users.  

<img width="915" alt="screen shot 2017-09-12 at 12 22 07 pm" src="https://user-images.githubusercontent.com/4230159/30305261-35fafcba-97b5-11e7-84f1-52c3ed51d4d2.png">

Thanks for getting back to me so quickly 😄

**Comment by karsai5** [comment]
I created a pull request updating the readme. Hopefully that makes it a bit clearer

https://github.com/dmfay/massive-js/pull/463

**Comment by dmfay** [comment]
Looks good, thanks!
