### ISSUE TITLE
Preventing SQL injection

### ISSUE THREAD

**Issue by kazitanvirahsan** [dmfay/massive-js#512]
We are using massive-js library for document searching using finddoc function. 

Can you please tell me how do I prevent the sql injection while passing 'Query options'?

From massive-js link, we can find out
https://massive-js.readthedocs.io/en/v2/simple_queries/

"order adds the value to the emitted query as an ORDER BY clause. Massive doesn't do any parsing or processing, so everything has to be exactly as you'd paste it into psql yourself."

and the code snippet from the above link

....products.find({
  in_stock: true
}, {
  order: [
    {field: "price", direction: "desc"},
    {field: "specs->>'height'", direction: "asc", type: "int"}
  ]
}, function (err, products) {...});

My question is 
How do we escape the value of 'field' and 'direction' from above? 

I don't mind doing it explicitly before handing over to massive-js.

**Comment by dmfay** [comment]
If you're accepting textual input directly into the `order` option, that's an [acknowledged vulnerability](https://dmfay.github.io/massive-js/options.html#sql-clauses) (also if you can upgrade definitely do so!). I've put off doing anything about it for a while now because there have been other features I've wanted more immediately and the applications I have using Massive don't allow direct input into `order` by design. I am open to suggestions and pull requests though!

**Comment by kazitanvirahsan** [comment]
Can you please also tell me if finddoc() function is using parameterised query?

**Comment by vitaly-t** [comment]
It would take to replace all the query generation with the code that instead generates a query-formatting template, using either [Index Variable](https://github.com/vitaly-t/pg-promise#index-variables) or [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters), and then pass all the formatting values in. The driver will take care about escaping everything correctly and prevent SQL injections.

**Comment by dmfay** [comment]
Nothing to do here.
