### ISSUE TITLE
Event Sourcing, CQRS, and Domain Driven Design

### ISSUE THREAD

**Issue by johncmunson** [dmfay/massive-js#611]
This isn't an issue at all, but more of a hope that that someone might help enlighten me.

Recently I discovered ES/CQRS/DDD and it crossed my mind that MassiveJS might somehow elegantly fit into this paradigm that has been gaining popularity as of late. However, I'm still new to this concept and am having trouble connecting the dots.

MassiveJS is an underrated piece of software and I'd love to see it get used in innovative new ways!

**Comment by dmfay** [comment]
Massive does this very well! The fundamental difference with all these shiny new models is that instead of doing CRUD on each table where applicable, you only write to some areas of your database, and you only read from others. For event sourcing, you have lots of `db.events.insert`, use triggers or materialized views to cache the current data-state, and then everything else is just reading those state tables and/or views. Nothing actually gets updated or deleted from the API layer, only in the event functions themselves. This would allow you to clear out everything except the `events` table and replay those to regenerate the state of your database at any point in time.

In fact, I'm currently working on a specialized manufacturing/RMA pipeline app using Massive to talk to an event-sourced database à la [Toby Hede's model](https://github.com/tobyhede/postgresql-event-sourcing), and it's not the first time I've taken this approach.

**Comment by johncmunson** [comment]
Very cool. Definitely going to spend some time studying Toby's model. I'm working on a TodoMVC application that I hope will demonstrate all of the most essential features in an architecture like this, and will likely be incorporating Massive. It will almost certainly end up being way over-engineered for the type of app that it is, but that's kinda the point.

Down the line, would you be open to a peer review and possibly a PR to the docs demonstrating how Massive could be used for ES/CQRS?

**Comment by dmfay** [comment]
Absolutely, it'd probably fit best as a new page somewhere around documents/transactions in the left table of contents.
