### ISSUE TITLE
Issues with $ placeholds in QueryFiles, pg-promise

### ISSUE THREAD

**Issue by ethanresnick** [dmfay/massive-js#649]
## Summary
First, a concrete issue: the bug identified in #642 is now fixed when the sql is passed directly to `db.query`, but it still exists when the SQL lives in a script file. The issue is that, when massive invokes the Executable generated from the file, somewhere around [here](https://github.com/dmfay/massive-js/blob/master/lib/executable.js#L53) the argument with the placeholder values again seems to get defaulted to an empty array, causing the same bug.

### Code demonstrating the behavior
```
// scriptFile.sql
CREATE TABLE test (
  id SERIAL PRIMARY KEY,
  column TEXT
);
INSERT INTO "test" ("column") VALUES (E'$65,478');
```

```
db.scriptFile(); // RangeError: Variable $65 out of range. Parameters array length: 0
```

## Expected behavior
Should run the insert with no error.

## pg-promise

While I understand that this issue can be fixed by not passing `pg-promise`'s formatter an empty array, so that it doesn't search the sql text for parameters, the fact that pg-promise is identifying `$65` *inside a string literal* as a potential parameter seems really, really problematic regardless.

First, I'm pretty sure it's wrong (i.e., I don't think parameters are allowed to occur within strings). More fundamentally, though, it's happening because `pg-promise` is parsing the query text itself and substituting in the parameter values, before sending the final concatenated string to the db server. 

Looking through `pg-promise`, this query parsing logic seems to be based around a lot of regular expressions — rather than a proper parser derived from a formal grammar — and it's bound have lots of bugs that are nearly guaranteed to create SQL injection vulnerabilities. Identifying "parameters" inside string literals is only one such bug. I actually found another bug today too, which I'll link here once I've opened an issue for it.

By contrast, the `node-postgres` library sends the user's query unaltered to the Postgres server, where postgres parses it to identify the parameters, with all its battle-tested parsing logic. (This happens through the [extended query protocol](https://www.postgresql.org/docs/10/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY). Massive should seriously consider switching to that approach for security.

**Comment by vitaly-t** [comment]
This is a lot of invalid assumptions in one single post that 😄

**Comment by dmfay** [comment]
So first, thanks for finding the bug! That shouldn't happen, and I'll have 5.5.2 up with a fix for query files shortly. On to the rest:

There's no real risk associated with false matches, assuming you test your code, since as you discovered they raise an error rather than permitting exploitation; and in the opposite case where an intended parameter _doesn't_ match, nothing is interpolated. For parameters that are correctly identified and interpolated, pg-promise sanitizes the values to ensure nothing goes out of bounds and introduces injection vulnerabilities.

To your second point, when you emit `SELECT $1...` to Postgres directly, $1 is a literal not an identifier. Not even casting it to a `name` (which takes double colons, `::`) allows you to do what you're thinking it does. With pg-promise you can use _named_ parameters to generate dynamic SQL, but again, 1) pg-promise sanitizes parameter values to ensure that they're properly escaped and quoted, and 2) false positives generate ordinary errors while false negatives aren't acted on.

None of this is to say that you can't shoot yourself in the foot with Massive. It's a data access framework and using data access frameworks safely takes a minimal amount of thought and care. There are even areas that _definitely_ open you up to injection if used unwisely -- check out the documentation for the `exprs` option! But this isn't the horrorshow you think it is.

And to give Vitaly his due, you _did_ kind of come in swinging telling me I should seriously consider abandoning his library :)

**Comment by ethanresnick** [comment]
>  That shouldn't happen, and I'll have 5.5.2 up with a fix for query files shortly.

Thanks!

> There's no real risk associated with false matches, assuming you test your code, since as you discovered they raise an error rather than permitting exploitation

Fair enough. 👍 

> To your second point, when you emit `SELECT $1...` to Postgres directly, $1 is a literal not an identifier. Not even casting it to a name (which takes double colons, ::) allows you to do what you're thinking it does.

Totally my mistake; I didn't realize you couldn't use Postgres prepared-statement placeholders for column names. Sorry to make this a bigger deal than it is.

**Comment by dmfay** [comment]
No worries :) It is actually 5.5.3 thanks to a minor versioning snafu but it's published.

**Comment by vitaly-t** [comment]
The change appears to be a continuation on #642.
