### ISSUE TITLE
Better way to decompose using postgres

### ISSUE THREAD

**Issue by dungeon2567** [dmfay/massive-js#654]
Decompose related objects with array_agg, subquery and json_build_object

Example:

(select array_agg(json_build_object('id', b.id)) from related where related.parentId = self.id)

![image](https://user-images.githubusercontent.com/31074903/49549142-04f6c500-f8cf-11e8-8bb4-6eb4878e7d97.png)

one to one 
![image](https://user-images.githubusercontent.com/31074903/49550573-37a2bc80-f8d3-11e8-9dad-39be761227a3.png)

**Comment by dmfay** [comment]
Well, it's _another_ way to decompose results. It stops being strictly better around the point where you have multiple joins or deeper levels of nesting, and it's a lot less flexible than applying a schema after the fact. I don't know if you're bringing this up as a suggestion for Massive, but the return on effort is not very good due to these limitations.

If you have fairly simple requirements and a lot of data to process, then yes, you'll likely see better performance using `array_agg` and `json(b)_build_object` instead of `decompose`. That's why Massive loads script files: the API features are about maximizing convenience for as many use cases as possible, but sometimes you really just need to fall back to SQL.
